# Generated by Django 4.2.20 on 2025-05-03 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='barCode',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='paymentStatus',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid')], default='Pending', max_length=100),
        ),
    ]
