# Generated by Django 4.2.20 on 2025-05-03 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_product_barcode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesitem',
            name='warehouse',
            field=models.ForeignKey(blank=True, help_text='The warehouse from which this product will be shipped', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.warehouse'),
        ),
    ]
