# Generated by Django 4.2.20 on 2025-05-03 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_salesorder_paymenttype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesitem',
            name='warehouse',
            field=models.ForeignKey(default=1, help_text='The warehouse from which this product will be shipped', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.warehouse'),
        ),
    ]
