# Generated by Django 4.2.20 on 2025-05-03 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_salesitem_warehouse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder',
            name='totalItems',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
