# Generated by Django 4.2.20 on 2025-05-03 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_purchaseorder_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='totalItems',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
