# Generated by Django 4.2.20 on 2025-05-03 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_purchaseorder_totalitems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='quantityAvailable',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
